version: '3'

services:
        dbos:
                image: mysql:5.7
                volumes: 
                        - mysql_storage_new:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: mayank
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: mydb

        wpos:
                image: wordpress:5.1.1-php7.3-apache
                volumes:
                        - wordpress_storage_new:/var/www/html
                restart: always
                depends_on:
                        - dbos
                ports: 
                        - 8081:80
                environment:
                        WORDPRESS_DB_HOST: dbos
                        WORDPRESS_DB_USER: mayank
                        WORDPRESS_DB_PASSWORD: redhat
                        WORDPRESS_DB_NAME: mydb

volumes:
        mysql_storage_new:
        wordpress_storage_new:

